In [10]:
import pandas as pd

df = pd.read_csv("../Data/demand_forecasting.csv")
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [21]:
renombrar = {
            "Date":"date",
             "Store ID":"store_id",
             "Product ID" : "product_id",
             "Category":"category",
             "Region": "region",
             "Inventory Level": "inventory_level",
             "Units Sold": "units_sold",
             "Units Ordered": "units_ordered",
             "Price": "price",
             "Discount": "discount",
             "Weather Condition": "weather_condition",
             "Promotion": "is_promotion",
             "Competitor Pricing": "competitor_pricing",
             "Seasonality": "seasonality",
              "Epidemic":  "is_epidemic",
             "Demand" : "demand"
}
df.rename(columns=renombrar, inplace=True)
print(list(df.columns))

['date', 'store_id', 'product_id', 'category', 'region', 'inventory_level', 'units_sold', 'units_ordered', 'price', 'discount', 'weather_condition', 'is_promotion', 'competitor_pricing', 'seasonality', 'is_epidemic', 'demand']

In [22]:
# Info del dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 76000 entries, 0 to 75999
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   date                76000 non-null  str
 1   store_id            76000 non-null  str
 2   product_id          76000 non-null  str
 3   category            76000 non-null  str
 4   region              76000 non-null  str
 5   inventory_level     76000 non-null  int64
 6   units_sold          76000 non-null  int64
 7   units_ordered       76000 non-null  int64
 8   price               76000 non-null  float64
 9   discount            76000 non-null  int64
 10  weather_condition   76000 non-null  str
 11  is_promotion        76000 non-null  int64
 12  competitor_pricing  76000 non-null  float64
 13  seasonality         76000 non-null  str
 14  is_epidemic         76000 non-null  int64
 15  demand              76000 non-null  int64
dtypes: float64(2), int64(7), str(7)
memory usage: 9.3 MB

In [23]:
# Dimensiones del Dataset
print(f"Cantidad de filas: {df.shape[0]}")
print(f"Cantidad de columnas: {df.shape[1]}")

Cantidad de filas: 76000
Cantidad de columnas: 16

In [26]:
# Rango de fechas
print(f"Fecha Inicio: {df['date'].min()}")
print(f"Fecha Fin: {df['date'].max()}")

Fecha Inicio: 2022-01-01
Fecha Fin: 2024-01-30

In [27]:
# Verificar valores Unicos
df.nunique().sort_values(ascending=True)

is_epidemic               2
is_promotion              2
region                    4
seasonality               4
weather_condition         4
store_id                  5
category                  5
discount                  6
product_id               20
units_sold              330
demand                  340
date                    760
units_ordered           996
inventory_level        1426
price                 15396
competitor_pricing    15963
dtype: int64

In [49]:
# Verificar duplicados
df.duplicated().sum()
print(f"Forma antes de eliminar duplicados: {df.shape}")
df.drop_duplicates(inplace=True)
print(f"Forma despues de eliminar duplicados: {df.shape}")

Forma antes de eliminar duplicados: (76000, 16)
Forma despues de eliminar duplicados: (76000, 16)

In [29]:
# Verificar nulos
df.isnull().sum()

date                  0
store_id              0
product_id            0
category              0
region                0
inventory_level       0
units_sold            0
units_ordered         0
price                 0
discount              0
weather_condition     0
is_promotion          0
competitor_pricing    0
seasonality           0
is_epidemic           0
demand                0
dtype: int64

In [53]:
pct_nulos = df.isnull().sum() / len(df) * 100
pct_nulos

date                  0.0
store_id              0.0
product_id            0.0
category              0.0
region                0.0
inventory_level       0.0
units_sold            0.0
units_ordered         0.0
price                 0.0
discount              0.0
weather_condition     0.0
is_promotion          0.0
competitor_pricing    0.0
seasonality           0.0
is_epidemic           0.0
demand                0.0
dtype: float64

In [47]:
# Casting de tipos de Datos

df["category"] = df["category"].astype('category')
df["region"] = df["region"].astype('category')
df["is_promotion"] = df["is_promotion"].astype('category')
df["weather_condition"] = df["weather_condition"].astype('category')
df["is_epidemic"] = df["is_epidemic"].astype('category')
df["seasonality"] = df["seasonality"].astype('category')
df['date'] = pd.to_datetime(df['date'])

df.dtypes

date                  datetime64[s]
store_id                        str
product_id                      str
category                   category
region                     category
inventory_level               int64
units_sold                    int64
units_ordered                 int64
price                       float64
discount                      int64
weather_condition          category
is_promotion               category
competitor_pricing          float64
seasonality                category
is_epidemic                category
demand                        int64
dtype: object

In [48]:
# Verificar
df.head()

,date,store_id,product_id,category,region,inventory_level,units_sold,units_ordered,price,discount,weather_condition,is_promotion,competitor_pricing,seasonality,is_epidemic,demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

In [56]:
# Guardar 
df.to_pickle('../Data/df_clean.pkl')